### ISSUE TITLE
vnc.html crash when trying to enter settings screen

### ISSUE THREAD

**Issue by geostant** [kanaka/noVNC#729] opened 2016-12-05 10:51 UTC
I'm trying to enter the settings screens on `vnc.html`
but I get an exception in the console:
```
Uncaught TypeError: Cannot read property 'startContainer' of null
    at Object._onMouseMove (content.js:822)
    at HTMLDocument.onMouseMove (content.js:781)
ui.js:574 Uncaught TypeError: Cannot read property 'classList' of null
    at idleControlbar (ui.js:574)
```

**Comment by samhed** [comment] 2016-12-05 10:57
Did you modify your vnc.html? You get the error because the UI code can't find this element: _'noVNC_control_bar_anchor'_

Perhaps you have an old cached version of vnc.html, try clearing your browser cache.

**Comment by geostant** [comment] 2016-12-05 11:23
@samhed 
Didn't modified the file.
I've cleared the cache and hard reset (right click on refresh button while in inspect mode)

When ever I try to hoover my mouse over the scaling option in the menu the app crash
I can try attach a gif animation :)

**Comment by samhed** [comment] 2016-12-05 11:46
I do understand the problem, no need for further explanation on that.. But I'm saying that your browser isn't finding the element called "noVNC_control_bar_anchor".

Could you open the JavaScript console and write the following and tell me the output:

    document.getElementById('noVNC_control_bar_anchor')

**Comment by geostant** [comment] 2016-12-05 13:30
It give me the whole element `noVNC_control_bar_anchor`
when I click on the `cog` symbol inside the anchor all is still well but when I hoover with my mouse
on `scaling mode` the app crash and give the error that I pasted before.

It also happen when trying to hoover with the mouse on `style` inside that `cog`.

I didn't mention that before but the screen goes all white with the following message:
`noVNC encountered an error.`

**Comment by samhed** [comment] 2016-12-05 13:33
Ok. What browser and browser version are you using?

**Comment by geostant** [comment] 2016-12-05 13:50
Chrome on OSX
Version 55.0.2883.75 (64-bit)

**Comment by samhed** [comment] 2016-12-05 14:44
Ok, so I went into the lab and tested the latest noVNC master on Chrome 49 on an old OSX 10.6 and Chrome 55 on OSX 10.11.6, I can not reproduce your issue. Everything works fine for me.

Do you run into the same problem when using a different browser?

**Comment by geostant** [comment] 2016-12-06 09:51
When I open the file directly in chrome it doesn't crash
it only happens when I actually browse to a live system.

**Comment by samhed** [comment] 2016-12-06 11:41
Well. The burden

**Comment by samhed** [comment] 2016-12-06 11:42
Well. The burden of proof falls on you here, as I said, I cannot reproduce your issue. You are doing something wrong and I don't think I can help you more here.

**Comment by samhed** [comment] 2016-12-06 11:44
I'm going to close this issue until I see something that points on an issue with noVNC.

**Closed by samhed** 2016-12-06 11:44 UTC
