### ISSUE TITLE
Unknown state: password

### ISSUE THREAD

**Issue by jettoblack** [kanaka/noVNC#660] opened 2016-09-14 20:21 UTC
Hi,

I'm using noVNC latest pull from git on a Raspberry Pi 2 running tightvncserver, which is configured to require a password.

If I connect to noVNC using the password in the URL parameters, e.g. http://server:port/vnc_auto.html?password=123 it connects successfully.  It also works if I connect to vnc.html and enter the server parameters in the dialog box: localhost, port, password.

If I just browse to the vnc_auto.html page without putting the password in the URL, I get a blank page with the message "Unknown state: password" at the top.  Is this expected behavior, or is it possible for this page to prompt for a password if required and not supplied on the URL?

Thanks.

**Comment by samhed** [comment] 2016-09-15 05:46
Duplicate of #646

**Closed by samhed** 2016-09-15 05:46 UTC
