### ISSUE TITLE
noVNC hangs after some time (variable)

### ISSUE THREAD

**Issue by sbellver** [kanaka/noVNC#556] opened 2015-11-27 09:57 UTC
We are using noVNC with Flask.

Once users are logged, we start a ERP and connect to postgresql.

Sometimes all logged users are log out suddenly, and they cannot login again upon we kill noVNC processes (really python processes) and start again the service.

The server cpu/ram is not a problem

¿Is any way to detect if noVNC works fine from terminal? I wonder if we can check noVNC and if it not respond, restart it automatically

**Comment by DirectXMan12** [comment] 2015-12-01 16:40
Are you talking about having problems with websockify?  Which version of websockify are you using?  Did websockify log anything?  Is there anything in the browser console?  What if you open a new noVNC browser session?  Does the new one hang immediately?  You shouldn't have to be restarting websockify.

**Comment by noah8713** [comment] 2015-12-01 23:18
I am facing the issue too. There are no error logs, but every 5 to six week, it shows novncproxy as running but it comes back one websockify restart. 
This is what I got from last run in logs
2015-11-16 03:07:12.328 21398 INFO nova.console.websocketproxy [-] handler exception: Cannot switch to MAINLOOP from MAINLOOP

**Comment by noah8713** [comment] 2015-12-01 23:20
I am using the same patch for websockify version >=0.6 for nova

**Comment by noah8713** [comment] 2015-12-01 23:23
I am using the same patch https://github.com/openstack/nova/commit/9386dd2fa301aee42da1e734b67670b317a0355f running on juno

**Comment by noah8713** [comment] 2015-12-01 23:28
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 878, in top_new_client
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     client = self.do_handshake(startsock, address)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 813, in do_handshake
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     self.RequestHandlerClass(retsock, address, self)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/nova/console/websocketproxy.py", line 105, in __init__
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     websockify.ProxyRequestHandler.__init__(self, *args, **kwargs)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 112, in __init__
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     SimpleHTTPRequestHandler.__init__(self, req, addr, server)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/SocketServer.py", line 638, in __init__
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     self.handle()
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 540, in handle
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     SimpleHTTPRequestHandler.handle(self)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     self.handle_one_request()
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     method()
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 506, in do_GET
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     if not self.handle_websocket():
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 498, in handle_websocket
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     self.send_close(exc.args[0], exc.args[1])
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py", line 393, in send_close
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     self.request.send(buf)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy   File "/opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/eventlet/greenio.py", line 342, in send
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy     total_sent += fd.send(data[total_sent:], flags)
2015-11-15 00:00:21.875 5062 TRACE nova.console.websocketproxy error: [Errno 32] Broken pipe

**Comment by noah8713** [comment] 2015-12-08 00:29
@DirectXMan12 : did the above details helped getting more insights? Hope we get it closed soon. :(

**Comment by DirectXMan12** [comment] 2015-12-08 15:44
Appologies, I've been a bit busy.  I'll try and take a look today.

**Comment by noah8713** [comment] 2015-12-08 17:49
sweet

**Comment by DirectXMan12** [comment] 2015-12-09 15:43
The "Cannot switch to MAINLOOP from MAINLOOP" may be caused by something like this: https://bugs.launchpad.net/nova/+bug/1029727 (we do log messages from our signal handlers), but it's hard to tell without a better reproduction case.  Can you try commenting out any calls to `self.msg` and `self.vmsg` in websockify and see if that solves your issue (in `multiprocessing_SIGCHLD` you'll have to add in a separate call to `multiprocessing.active_children()` to compensate for commenting out the call in `vmsg`)?

**Comment by noah8713** [comment] 2015-12-09 19:18
You mean these are just extra calls? So this is what I always see as a happy scenario in my logs:
2015-12-09 12:16:11.145 96420 INFO nova.console.websocketproxy [-] 10.x.x.x: ignoring empty handshake
2015-12-09 12:16:11.150 75680 DEBUG nova.console.websocketproxy [-] Reaing zombies, active child count is 0 vmsg /opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py:828

**Comment by noah8713** [comment] 2015-12-09 19:23
I am already doing that:
def multiprocessing_SIGCHLD(self, sig, stack):
        self.vmsg('Reaing zombies, active child count is %s', len(multiprocessing.active_children()))

**Comment by noah8713** [comment] 2015-12-09 19:23
so I just need to comment out extra calls right?

**Comment by noah8713** [comment] 2015-12-09 19:34
Also is there anything about Line 98 for #TODO a point of concern ? Since I just saw kilo version of websockify which is different @ https://github.com/openstack/nova/blob/stable/kilo/nova/console/websocketproxy.py

**Comment by noah8713** [comment] 2015-12-09 21:24
@DirectXMan12  Please let me know

**Comment by DirectXMan12** [comment] 2015-12-09 22:12
You should just need to comment out the calls to `self.msg` or `self.vmsg`.  In the case of `multiprocessing_SIGCHLD`, it would look like:

```python
def multiprocessing_SIGCHLD(self, sig, stack):
    #self.vmsg('Reaing zombies, active child count is %s', len(multiprocessing.active_children()))
    multiprocessing.active_children()
```

Most of the calls to `msg` and `vmsg` are just logging calls.  The `multiprocessing.active_children()` actually reaps zombies, so you'll need to retain that call (as I indicated just above) in some form to prevent websockify from leaving zombie processes around.

**Comment by noah8713** [comment] 2015-12-09 22:41
@DirectXMan12  Alright I commented out self.msg and self.vms in nova/console/websocketproxy.py
I also changed the above code in websocket/websockify.py  and restarted nova-novncproxy. Its running. Might have to monitor for some time to see if it is fixed.

Also for websockify , does the latest py version has this already fixed since for now I have just updated in lib folder for python?

**Comment by noah8713** [comment] 2015-12-09 22:56
@DirectXMan12 Sorry above solution to comment out does not work. After commenting self.msg and self.vmsg in nova/console always auto kills the nova-novncproxy process. I also commented out the websockify code as you suggested above and it does not work. Gives below error:
2015-12-09 15:38:11.936 75680 DEBUG nova.console.websocketproxy [-] Closing socket listening at 0.0.0.0:8081 vmsg /opt/openstack/nova/2014.2.2.r30/lib/python2.7/site-packages/websockify/websocket.py:828

**Comment by DirectXMan12** [comment] 2015-12-10 02:12
hmm... can you send me the patch you are using?

**Comment by noah8713** [comment] 2015-12-10 02:31
Sure , here it is:
https://github.com/openstack/nova/blob/9386dd2fa301aee42da1e734b67670b317a0355f/nova/console/websocketproxy.py

**Comment by noah8713** [comment] 2015-12-10 19:09
@DirectXMan12 any updates?

**Comment by DirectXMan12** [comment] 2015-12-10 20:09
Sorry, I'm mostly looking at this in the evenings.  It's a bit hard to debug this issue, because I don't have a reproduction case (or, at least, not one that doesn't take multiple weeks to trigger).  Commenting out uses of vmsg and msg in your copy of websockify shouldn't cause your websockify to stop working entirely.  Assuming you're on websockify v0.6.1, if you commented out the uses of logging in the signal handlers, you should have a diff like:

```diff
 diff --git a/websockify/websocket.py b/websockify/websocket.py
index 5031069..d6698dc 100644
--- a/websockify/websocket.py
+++ b/websockify/websocket.py
@@ -848,25 +848,26 @@ class WebSocketServer(object):
         raise self.Terminate()
 
     def multiprocessing_SIGCHLD(self, sig, stack):
-        self.vmsg('Reaing zombies, active child count is %s', len(multiprocessing.active_children()))
+        #self.vmsg('Reaing zombies, active child count is %s', len(multiprocessing.active_children()))
+        multiprocessing.active_children()
 
     def fallback_SIGCHLD(self, sig, stack):
         # Reap zombies when using os.fork() (python 2.4)
-        self.vmsg("Got SIGCHLD, reaping zombies")
+        #self.vmsg("Got SIGCHLD, reaping zombies")
         try:
             result = os.waitpid(-1, os.WNOHANG)
             while result[0]:
-                self.vmsg("Reaped child process %s" % result[0])
+                #self.vmsg("Reaped child process %s" % result[0])
                 result = os.waitpid(-1, os.WNOHANG)
         except (OSError):
             pass
 
     def do_SIGINT(self, sig, stack):
-        self.msg("Got SIGINT, exiting")
+        #self.msg("Got SIGINT, exiting")
         self.terminate()
 
     def do_SIGTERM(self, sig, stack):
-        self.msg("Got SIGTERM, exiting")
+        #self.msg("Got SIGTERM, exiting")
         self.terminate()
 
     def top_new_client(self, startsock, address):
```

If that patch doesn't work, an OpenStack Guru Meditation Report would be useful, since it appears that you're running websockify through a version of OpenStack with GMR support on Nova services.

**Comment by noah8713** [comment] 2015-12-10 22:28
This is more clear now. I also commented the self.msg and self.vmsg earlier in nova/console/websocket.py folder. My services are running fine now ,post restart after code change as you suggested above. Just keeping this bug open and I will monitor for a week or more and we can close it then if it does not hang.

Thanks @DirectXMan12

**Comment by DirectXMan12** [comment] 2015-12-10 23:40
Sounds good.  Hopefully we can get this cleared up (at which point I will have to figure out how to deal with the lack of logging in the signal handling code...)

**Comment by noah8713** [comment] 2015-12-18 20:18
@DirectXMan12  Are you planning to role out this patch in upstream? If so, I can just cherrry pick so that my pip requirement will just pull in the version with latest patch or hot-fix patch whatever? thoughts?

**Comment by DirectXMan12** [comment] 2015-12-22 16:16
@noah8713 I'll release a new version of websockify kanaka/websockify#217 merges

**Comment by noah8713** [comment] 2016-01-11 21:04
@DirectXMan12  please help to merge the commit on websockify so that we can close this issue

**Comment by DirectXMan12** [comment] 2016-01-11 21:28
@noah8713 I was waiting to make sure @kanaka didn't have any further comments.  All merged now.

**Closed by DirectXMan12** 2016-01-11 21:28 UTC
Labels: bug

**Comment by hellochosen** [comment] 2019-01-05 06:33
Hi, all. I just update the code following [1] and [2], it still get the error from nova-novncproxy.log: handler exception: [Errno 32] Broken pipe.

[1] https://github.com/novnc/websockify/commit/6f0e06772a87f84f6f1e6ed7ee693bf23b0b0107
[2] https://github.com/openstack/nova/commit/9386dd2fa301aee42da1e734b67670b317a0355f
