### ISSUE TITLE
WebSocket not closed after some errors, RFB.connect() never ends.

### ISSUE THREAD

**Issue by Augustin82** [kanaka/noVNC#538] opened 2015-10-05 12:47 UTC
Hi all,

in our app, we sometimes try to connect to a WebSocket before everything is set-up correctly (VNC server started, websockify launched, etc.). To make this transparent for the user, we have written a custom updateStatus method: when the state is "failed", we increment a counter and retry, until we reach a certain number of retries, at which point we stop retrying.

This is how it looks:

```
function updateState(rfb, state, oldstate, msg) {
    /* some code */
    switch (state) {
        case 'failed':
            level = "error";
            setTimeout(
                function() {
                    if (retries < maxRetries) {
                        retries++;
                        sendConnect();
                    }
                }
                , 2000);
            break;
    /* more code */
}

/* all variables are initialized somewhere */
function sendConnect() {
    $.getJSON(
            getName,
            function(data) {
                path += "/?name=" + data.name;
                rfb.connect(url, port, password, path);
            }
    );
}
```

Now the problem: when the page is open, we launch sendConnect(). Let's assume the websockify is not started: connection fails (in the JS console, the following two messages are seen in close succession: "WebSocket on-error event", "WebSocket on-close event"). updateState fires normally, and sendConnect is called a second time, as expected. Only this time, it hangs there and nothing further happens. In the JS console, only one message is seen: "WebSocket on-error event".

It seems the WebSocket is never closed, so connect never returns, so our custom sendConnect never does.

I have attempted to fix this by modifying rfb.js, but I have little idea what I am doing, and it is likely not a good modification:
```
Original: (line 214 of rfb.js)
this._sock.on('error', function (e) {
    Util.Warn("WebSocket on-error event");
});

Modified:
this._sock.on('error', function (e) {
    Util.Warn("WebSocket on-error event");
    this._fail("Got unexpected WebSocket connection");
}.bind(this));
```

When using this modification, our logic works as expected.

Could anyone please help me understand what's going on, and how we could improve our code to fix the problem?

Thanks a bunch!

**Comment by Augustin-SysFera** [comment] 2015-10-13 14:15
Just a quick update: after some tests on our side, our modification seems to be working in our use cases.

I am still very much unsure of the further consequences of this.

**Comment by DirectXMan12** [comment] 2016-01-06 21:07
I'm closing this since you seem to have things working on your end.  I'm not sure what's causing the issue here (I cannot reproduce the hanging when websockify isn't running).

**Closed by DirectXMan12** 2016-01-06 21:07 UTC
Labels: bug, question
