### ISSUE TITLE
"404 File not found" on Demo page

### ISSUE THREAD

**Issue by z3ntu** [kanaka/noVNC#515] opened 2015-08-16 13:34 UTC
On [this](https://kanaka.github.io/noVNC/demo1.html) page (demo page) the page tries to get [this](https://kanaka.github.io/noVNC/noVNC/include/vnc.js) JS file which doesn't exist. Using Chrome 46.0.2478.0 dev (64-bit) on Ubuntu 15.04.

**Comment by samhed** [comment] 2015-08-17 07:04
Duplicate of #278

**Closed by samhed** 2015-08-17 07:04 UTC
Labels: duplicate

**Comment by krosoftware** [comment] 2018-11-20 11:10
Hello
Demo on site https://novnc.com/noVNC/vnc.html does not work. Is there other demo, please?

**Comment by samhed** [comment] 2018-11-21 15:08
I answered on your other issue #1164
