### ISSUE TITLE
Detecting touchscreen causes mouse not to work

### ISSUE THREAD

**Issue by RickGlimmer** [kanaka/noVNC#510] opened 2015-07-15 16:58 UTC
On a Surface Pro 3 which has a touchscreen it is not possible to use the mouse.
I think the code in input.js where a feature detect is done for touchstart only attaches the touch events and not the mouse.
It might work better when using  pointer events as they are now considered the best way of handling all kinds of pointer input devices.
I do not have a test environment otherwise i would have a go at it.

**Comment by DirectXMan12** [comment] 2015-08-11 17:40
See also #369 and #476.  Unfortunately, I don't have a Windows-based touch device to test this with.  If you do, or you know someone who does, we'd be glad to accept a PR

**Comment by zarmhast** [comment] 2016-05-01 05:46
Please see PR #608 . I have windows and the patch was tested together with the current master branch.
Both touchscreen and mouse worked without any issues in chrome. Please let me know if this causes issues with touchscreen browsers in Linux/OSX (would not expect it to).

Thank you.

**Comment by samhed** [comment] 2016-05-02 08:19
Your code does not work on Android and iOS.

**Comment by zarmhast** [comment] 2016-05-02 23:09
@samhed Hello, thank you for testing my changes. Since I do not own any iOS devices, I would really appreciate if you would elaborate about what exactly does not work?
After a few attempts noVNC in chrome on Android was finally able to establish a VNC connection and I was able to interact with windows on a remote machine by simply touching the screen wherever I needed to.

**Comment by samhed** [comment] 2016-05-10 11:30
> After a few attempts noVNC in chrome on Android was finally able to establish a VNC connection and I was able to interact with windows on a remote machine by simply touching the screen wherever I needed to.

The mousedown event isn't triggered when you start touching the screen, it's sent together with mouseup when you lift your finger. Yes, clicks go through, but it's impossible to do drag-and-drop or mouse selection rectangles for example. It's also impossible to use panning.

**Comment by zarmhast** [comment] 2016-05-10 12:02
> Yes, clicks go through, but it's impossible to do drag-and-drop or mouse selection rectangles for example. It's also impossible to use panning.
@samhed thank you, that is helpful. Now I have a better idea of what needs to be fixed.

**Comment by zarmhast** [comment] 2016-06-05 00:52
This time I know that the issue is fixed with pull request #619. @samhed, thank you for your input, it helped.

**Comment by samhed** [comment] 2016-10-19 22:58
Fixed by 4b20f2364c3924e89ccedf7eda56af322e5e9e1e

**Closed by samhed** 2016-10-19 22:58 UTC
Labels: bug
