### ISSUE TITLE
Check boxes don't work properly when connected

### ISSUE THREAD

**Issue by dcommander** [kanaka/noVNC#587] opened 2016-03-19 16:27 UTC
Referring to https://github.com/dcommander/noVNC/commit/abda153973feeebc781f3d93fdc25901208c6175 (work in progress), I'm working on the ability to control Tight encoding settings "on the fly" while the viewer is connected.  I have that aspect of it working properly with TightVNC-compatible servers (including TurboVNC, TigerVNC, and UltraVNC), but I'm running into a weird GUI issue that I can't seem to solve after many hours of hacking at it.  The problem is that, when I pop up the settings panel while the viewer is connected, the check boxes don't work.  They don't fire the onchange or oninput events, and clicking on them doesn't change their state.  I even tried replacing them with radio buttons, but those don't fire either.  However, other controls work properly, and the check boxes can be set or unset programmatically-- they just don't work when you click on them.

Hoping someone might give me a clue as to what's going on, because I'm new to this stuff.

**Comment by dcommander** [comment] 2016-03-19 16:29
NOTE:  To those who might read this quickly and have a knee-jerk response, such as "but the check boxes are disabled during connection"-- I'm referring to new check boxes that my GUI specifically created, not the existing check boxes like "Encrypt".

**Comment by samhed** [comment] 2016-12-02 08:14
Sorry for the late response, it sounds like a weird behavior. Did you find the cause?

**Comment by 4knahs** [comment] 2016-12-02 11:41
just disable the grab of the mouse events by NoVNC or modify the grab area (canvas).

**Comment by samhed** [comment] 2016-12-02 12:37
@4knahs good point, that is with very high likelihood the issue here! Closing this

**Closed by samhed** 2016-12-02 12:37 UTC
Labels: bug

**Comment by dcommander** [comment] 2016-12-02 14:04
Confirmed that this is grab-related.  I'll probably have to modify my fork of the viewer so that it temporarily disables grabbing when the user pops up the configuration dialog.  Thanks for the hint!
